"""changed doctor to support first and last name

Revision ID: 1d062bb4280b
Revises: 75eb466d00b7
Create Date: 2025-05-02 22:27:59.333803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d062bb4280b'
down_revision = '75eb466d00b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('doctors', sa.Column('last_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'last_name')
    op.drop_column('doctors', 'first_name')
    # ### end Alembic commands ###
