"""added dob to doctor

Revision ID: 954d6434947c
Revises: e0ce42302360
Create Date: 2025-05-07 22:47:31.106555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954d6434947c'
down_revision = 'e0ce42302360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('dob', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'dob')
    # ### end Alembic commands ###
