"""added allergies

Revision ID: c7e88c234930
Revises: 1d062bb4280b
Create Date: 2025-05-07 14:10:07.957436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e88c234930'
down_revision = '1d062bb4280b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
